export const GET_BRANDS_LIST = "GET_BRANDS_LIST";
export const GET_BRANDS_LIST_SUCCESS = "GET_BRANDS_LIST_SUCCESS";
export const GET_BRANDS_LIST_FAILURE = "GET_BRANDS_LIST_FAILURE";

export const GET_BRAND_DETAILS = "GET_BRAND_DETAILS";
export const GET_BRAND_DETAILS_SUCCESS = "GET_BRAND_DETAILS_SUCCESS";
export const GET_BRAND_DETAILS_FAILURE = "GET_BRAND_LIST_FAILURE";

export const GET_CHOCOLATES_LIST = "GET_CHOCOLATES_LIST";
export const GET_CHOCOLATES_LIST_SUCCESS = "GET_CHOCOLATES_LIST_SUCCESS";
export const GET_CHOCOLATES_LIST_FAILURE = "GET_CHOCOLATES_LIST_FAILURE";

export const GET_CHOCOLATE_DETAILS = "GET_CHOCOLATE_DETAILS";
export const GET_CHOCOLATE_DETAILS_SUCCESS = "GET_CHOCOLATES_DETAILS_SUCCESS";
export const GET_CHOCOLATE_DETAILS_FAILURE = "GET_CHOCOLATES_DETAILS_FAILURE";